#Routing for Dami Bundle

#RESTFUL POST API for storing contact information and sending mail
contact_store:
    path: /contact/store
    controller: App\Dami\SocialPlacesBundle\SocialPlacesBundle::store
    methods:    [POST]